### ISSUE TITLE
about segmentation

### ISSUE THREAD

**Issue by tyduck** [MarvinTeichmann/KittiBox#10]
I use image in KITTI and regard pred_up in modules['arch'].inference as segmentaion result, but I find this segmentaion result is worse than that in paper "MultiNet Real-time Joint Semantic Reasoning for Autonomous Driving", is it because pred_up not be the segmentation result ?

**Comment by MarvinTeichmann** [comment]
You are in the wrong repository. My Segmentation Code can be found in the [KittiSeg](https://github.com/MarvinTeichmann/KittiSeg) repo. How inference is done is shown in the [demo.py](https://github.com/MarvinTeichmann/KittiSeg/blob/master/demo.py).
