### ISSUE TITLE
Cannot download vgg16.npy from dropbox

### ISSUE THREAD

**Issue by GoLancer** [MarvinTeichmann/KittiBox#11]

**Comment by MarvinTeichmann** [comment]
The file seems to be alive to me: https://dl.dropboxusercontent.com/u/50333326/vgg16.npy

**Comment by villanuevab** [comment]
The Dropbox file is no longer available (404 error), but I was able to download the same file from here: ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy

**Comment by GoLancer** [comment]
Solved my problem. Thank you @villanuevab
