### ISSUE TITLE
Submodule import or util folder missing

### ISSUE THREAD

**Issue by bigsnarfdude** [MarvinTeichmann/KittiBox#14]
Hey MarvinTeichmann,

I was reviewing https://github.com/MarvinTeichmann/KittiBox/blob/master/demo.py and there is a line

Line:
`from utils import train_utils as kittibox_utils`

and I'm getting an import error ...

Error: 
`ImportError: No module named 'utils'`

Do you recall where this "kittibox_utils" lives?

**Comment by MarvinTeichmann** [comment]
Hi bigsnarfdude,

yes, it should be right in the folder [incl](https://github.com/MarvinTeichmann/KittiBox/blob/master/incl/utils).

Marvin

**Comment by bigsnarfdude** [comment]
Thanks. Demo.py works like a charm! Closing.

**Comment by MarvinTeichmann** [comment]
Cool. My I ask what caused and how you solved the problem? I did assume that the whole repository works out of box for most users.

**Comment by bigsnarfdude** [comment]
I had to manually create RUN folder and I refollowed the instructions. I think I forgot the submodule command as I was setting up all three repos at once.  I'm running on Ubuntu 14.04 with Python3.4 with Cuda8 and CuDNN5.1

**Comment by weisq2691** [comment]
hi @bigsnarfdude 
I just touched tensorflow soon.I want run kiitiBox in windows environment，but i do not understand the last step.
      2.Run cd submodules/utils && make to build cython code
Can you tell me how to build cython code?
thanks~

**Comment by bigsnarfdude** [comment]
hi @weisq2691 
I've never used Windows environment. The instructions are linux/unix OS command line based instructions only:

`
cd submodules/utils
` 

`
make
`
