### ISSUE TITLE
ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiBox_pretrained.zip  I cannot download it .

### ISSUE THREAD

**Issue by yeyang1021** [MarvinTeichmann/KittiBox#16]
the URL cannot work. in demo.py
Could you give us another available URL to download it?

It is mistake. It can be download by browser or create a folder RUNS

**Comment by MarvinTeichmann** [comment]
The FTP server is experiencing high load at the moment. See also this [issue](https://github.com/MarvinTeichmann/KittiSeg/issues/19#issuecomment-285726541). If download does not work, try again in a view minutes / hours.

**Comment by yeyang1021** [comment]
Thank you for your answer. I think you just add a RUNS folder in your code, the problem will disappear.

**Comment by wuyuzaizai** [comment]
@yeyang1021 thx, you're right ,just add a RUNS folder, it's work!
