### ISSUE TITLE
incl/utils/stitch_wrapper.so: undefined symbol

### ISSUE THREAD

**Issue by chrjxj** [MarvinTeichmann/KittiBox#18]
when I run the demo.py, I got the following errors. Looks like the ./submodules/utils is not built properly, missing some add'l lib in linkage, maybe. Would you please give me some directions? thanks. 

2017-03-18 10:50:40,035 INFO Weights loaded successfully.
2017-03-18 10:50:40,035 INFO Starting inference using data/demo.png as input
Traceback (most recent call last):
  File "demo.py", line 206, in <module>
    tf.app.run()
  File "/home/jin/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 172, in main
    min_conf=0.50, tau=hypes['tau'], color_acc=(0, 255, 0))
  File "incl/utils/train_utils.py", line 103, in add_rectangles
    from stitch_wrapper import stitch_rects
ImportError: incl/utils/stitch_wrapper.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E

**Comment by MarvinTeichmann** [comment]
Never ran across this error, sry.

**Comment by bigsnarfdude** [comment]
@chrjxj did you Initialize all submodules: `git submodule update --init --recursive`
`cd submodules/KittiBox/submodules/utils/ && make` to build cython code

**Comment by chrjxj** [comment]
@bigsnarfdude  Yes, I did. It looks like a linkage error. Maybe some lib was setup incorrectly ...
My server goes down for a few days and don't have chance to fix this yet... but do need this working badly.

**Comment by MarvinTeichmann** [comment]
No clue what is going wrong. Try to rebuild. Close for now until there is an update about this issue.

**Comment by kongmo** [comment]
I encountered the same problem. After re-clone and rebuild, it didn't work out. Have anyone solved it?

**Comment by kongmo** [comment]
after execute this: conda install libgcc, then it worked.

**Comment by chrjxj** [comment]
thanks. I will give it a try

**Comment by jesseseales** [comment]
I was having a similar problem and think it was some sort of issue with things not being configured for python 3. I got it to work after running ` $ make all-python3 ` from  `KittiBox/incl/utils`
