### ISSUE TITLE
dynamic module does not define module export function (PyInit_stitch_wrapper) 

### ISSUE THREAD

**Issue by LovPe** [MarvinTeichmann/KittiBox#20]
i use python 3.5 on windows and built 'stitch_wrapper.pyx' with visual C++ 2015 build tool. 
The tensorflow version is 1.0
when i run demo.py, i get this error:
  ImportError: dynamic module does not define module export function (PyInit_stitch_wrapper)
I wonder that if this code can only  run on python 2.7?  do any one success run this on python 3.5

**Comment by MarvinTeichmann** [comment]
I have not much experience using visual c++. Try to use [make](https://www.gnu.org/software/make/). It works well.

**Comment by MarvinTeichmann** [comment]
Closed for now. Properly an windows errror. Please look at #23 to fix.
