### ISSUE TITLE
windows installation issues -- the solutions are here

### ISSUE THREAD

**Issue by ipadyouku** [MarvinTeichmann/KittiBox#23]
https://github.com/Khaos/DD2017/tree/kittiEdit/Code/KittiBox

**Comment by MarvinTeichmann** [comment]
A direct link is now provided in the Readme.

**Comment by weisq2691** [comment]
hi @ipadyouku I encountered a problem when i run `python setup.py build_ext --inplace`
`running build_ext
skipping 'stitch_wrapper.cpp' Cython extension (up-to-date)
building 'stitch_wrapper' extension
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Anaconda3\envs\tensorflow\include -ID:\Anaconda3\envs\tensorflow\include -ID:\VS2015\VC\INCLUDE -ID:\VS2015\VC\ATLMFC\INCLUDE "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.
14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Progr
am Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /EHsc /Tpstitch_wrapper.cpp /Fobuild\temp.win-amd64-3.5\Release\stitch_wrapper.obj
error: command 'cl.exe' failed: No such file or directory
`
My VS2015 is working well.
Can you tell me how to solve this problem?
Thanks~
