### ISSUE TITLE
Modify summary

### ISSUE THREAD

**Issue by nghiattran** [MarvinTeichmann/KittiBox#25]
Is there any way to add or remove summary for certain fields?

**Comment by MarvinTeichmann** [comment]
I don't quite understand what your goal is. Can you give an example? 

An easy way to print more information and also add it to tensorboard is to include the corresponding tensor to `eval_list`. Have a look [here](https://github.com/MarvinTeichmann/KittiBox/blob/master/decoder/fastBox.py#L432). Is this what you are trying to archive?>\

**Comment by nghiattran** [comment]
Sorry, I didn't make it clear. I am trying to reduce number of summaries to speed up training process. Currently, there are roughly 66 summaries (22 layers * 3 type of summary) but I am only interested in a few a them.

**Comment by MarvinTeichmann** [comment]
It is not implemented. However it should be easy to adopt the files to reduce summaries. Easiest way is to remove the lines from the functions `_activation_summary` and `weight_summary`.

However before you do this, I would propose to test whether this indeed speed ups the training process. TensorVision has a switch `--nosummary`. This deactivates summary completely.

**Comment by nghiattran** [comment]
I tested and it turned out that turning off summaries does not speed up training significantly.
