### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc Aborted (core dumped)

### ISSUE THREAD

**Issue by neuralearner** [MarvinTeichmann/KittiBox#29]
Hi, great work so far! I've been experimenting with fastbox and have been able to get the demo to work. However, when I try to retrain my own model with the same Kitti dataset I'm getting the following error message when I run: python train.py

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by nghiattran** [comment]
This sounds like you don't have enough memory to hold a batch. What is your `batch_size` value? How much memory do you have on GPU? Try to decrease your `batch_size` until tensorflow stop complaining about it.

**Comment by MarvinTeichmann** [comment]
Closed due to inactivity. Should be fixable with a smaller batch size or bigger GPU memory. I recommend using 1080 TI for deep learning.
