### ISSUE TITLE
Kitti labels

### ISSUE THREAD

**Issue by Yaredoh** [MarvinTeichmann/KittiBox#33]
Hi,
How can we prepare labels for our own dataset just like kitti image detection label? "Misc 0.00 0 -1.82 804.79 167.34 995.43 327.94 1.63 1.48 2.37 3.23 1.59 8.55 -1.47
Car 0.00 0 -1.67 657.39 190.13 700.07 223.39 1.41 1.58 4.36 3.18 2.27 34.38 -1.58
"
Do you have any idea how can we generate these vectors form our image? Any software that can generate the rectangle vector numbers. I want to use it for my own dataset.

Thanks.

**Comment by MarvinTeichmann** [comment]
You can annotate the images yourself or use crowedsourcing like: https://www.mturk.com/mturk/welcome
