### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by lujian9328** [MarvinTeichmann/KittiBox#41]
I was training KittiBox with my resize Kitti images data. Such that I modified data  in label files. And in the evaluation process, it need KittiObject2 to support evaluation. But how does val_gt and val_pred produce? Since README.md in KittiObject2 does not tell me about val_gt and val_pred.

**Comment by debapriyamaji** [comment]
Hi @lujian9328 , @MarvinTeichmann 
  What is the conclusion regarding this? I am not able to evaluate my model using KittiObject2.  I am getting the following error: 'returned non-zero exit status -11' . 
   Apart from the four coordinates and the class type, what should the other fields contain? I tried certain combinations:
-  Don't care for all redundant fields. E.g.
        Car -1 -1 -10 169.31 289.59 242.85 395.94 -1 -1 -1 -1000 -1000 -1000 10 
- In line with the predicted o/p file. E.g.
        Car 0 1 0 168.83 309.59 238.03 407.51 0 0 0 0 0 0 0
-  Some random values for unused fields. E.g.
        Car 0.89 0 2.29 168.83 309.59 238.03 407.51 1.57 1.67 4.14 1.70 1.33 7.59 1.25 

However, none of the above worked. Please let me know how did you generate the GT file? Initially,  I assumed that all fields apart from the class category and (x1, y1, x2, y2)  does not hold any significance for  KittiBox training. How far is it true?
