### ISSUE TITLE
I downloaded vgg16.npy, but still "not found"

### ISSUE THREAD

**Issue by anonym24** [MarvinTeichmann/KittiBox#44]
`ERROR File 'DATA/vgg16.npy' not found. Download it from ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy
`

![screenshot_1](https://user-images.githubusercontent.com/8851301/30533264-1e1d3e90-9c61-11e7-9807-396a9527f17c.png)
![screenshot_2](https://user-images.githubusercontent.com/8851301/30533265-1e26aea8-9c61-11e7-8123-977dd04fc96e.png)

**Comment by qmanalex** [comment]
I have the same problem. @anonym24  Have you solved this problem? Can you teach me?

**Comment by MartinQingM** [comment]
I meet the same problem. You need to be more careful.
This file need to be move to 'DATA‘ as it is said in the ERROR

**Comment by anonym24** [comment]
yes I did so that time

**Comment by ChinmayKalyankar** [comment]
where that 'DATA ' folder must be created ??
