### ISSUE TITLE
Cannot build evaluate_object

### ISSUE THREAD

**Issue by hongxuenong** [MarvinTeichmann/KittiBox#55]
I had following warnings when calling "cd submodules/KittiObjective2/ && make"

g++ -O3 -DNDEBUG -o evaluate_object2 evaluate_object.cpp
evaluate_object.cpp: In function ‘void saveAndPlotPlots(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::vector<double>*, bool)’:
evaluate_object.cpp:625:20: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
     system(command);
                    ^
evaluate_object.cpp:630:18: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(command);
                  ^
evaluate_object.cpp:632:18: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(command);
                  ^
evaluate_object.cpp:634:18: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(command);
                  ^
evaluate_object.cpp: In function ‘bool eval(std::__cxx11::string, std::__cxx11::string, Mail*)’:
evaluate_object.cpp:652:40: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(("mkdir " + plot_dir).c_str());
                                        ^
There is still a "evaluate_object2" generated.
Also when I try to test it, it produce errors as shown below:
2 val_pred val_gt
Thank you for participating in our evaluation!
Starting to evaluate Results found in: val_pred
mkdir: cannot create directory ‘val_pred/plot’: File exists
Loading detections...
  done.
sh: 1: gnuplot: not found
sh: 1: gnuplot: not found
Error: /undefinedfilename in (car_detection.eps)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:1198/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.18: Unrecoverable error, exit code 1
sh: 1: pdfcrop: not found
Evaluation Succesfull. Results can be found:
val_pred /results 

And during training, program terminates whenever evaluation script is called.

**Comment by screamdw** [comment]
@hongxuenong @MarvinTeichmann 
hello, .How is your problem solved? When I run"cd submodules/KittiObjective2/ && make", I get the following error:

➜  KittiObjective2 git:(e080afd) ✗ make
g++ -O3 -DNDEBUG -o evaluate_object2 evaluate_object.cpp
evaluate_object.cpp: In function ‘void saveAndPlotPlots(std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::vector<double>*, bool)’:
evaluate_object.cpp:625:20: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
     system(command);
                    ^
evaluate_object.cpp:630:18: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(command);
                  ^
evaluate_object.cpp:632:18: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(command);
                  ^
evaluate_object.cpp:634:18: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(command);
                  ^
evaluate_object.cpp: In function ‘bool eval(std::__cxx11::string, std::__cxx11::string, Mail*)’:
evaluate_object.cpp:652:40: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(("mkdir " + plot_dir).c_str());
                                        ^
/tmp/ccXsMPoX.o：在函数‘void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.147]’中：
evaluate_object.cpp:(.text+0x2e)：对‘std::__throw_logic_error(char const*)’未定义的引用
evaluate_object.cpp:(.text+0x89)：对‘std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)’未定义的引用
......
/tmp/ccXsMPoX.o：在函数‘main’中：
evaluate_object.cpp:(.text.startup+0x259)：对‘operator new(unsigned long)’未定义的引用
evaluate_object.cpp:(.text.startup+0x294)：对‘operator delete(void*)’未定义的引用
evaluate_object.cpp:(.text.startup+0x2a8)：对‘operator delete(void*)’未定义的引用
evaluate_object.cpp:(.text.startup+0x2bc)：对‘operator delete(void*)’未定义的引用
evaluate_object.cpp:(.text.startup+0x2cf)：对‘operator delete(void*)’未定义的引用
evaluate_object.cpp:(.text.startup+0x2fb)：对‘operator delete(void*)’未定义的引用
/tmp/ccXsMPoX.o:evaluate_object.cpp:(.text.startup+0x337): 跟着更多未定义的参考到 operator delete(void*)
/tmp/ccXsMPoX.o：在函数‘_GLOBAL__sub_I__Z11CLASS_NAMESB5cxx11’中：
evaluate_object.cpp:(.text.startup+0x35a)：对‘std::ios_base::Init::Init()’未定义的引用
evaluate_object.cpp:(.text.startup+0x369)：对‘std::ios_base::Init::~Init()’未定义的引用
/tmp/ccXsMPoX.o:(.eh_frame+0x233)：对‘__gxx_personality_v0’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:3: recipe for target 'make' failed
make: *** [make] Error 1
How can I solve it? Thanks!
