### ISSUE TITLE
model in git vs model in Kittibox_pretrained

### ISSUE THREAD

**Issue by BenMacKenzie** [MarvinTeichmann/KittiBox#7]
They appear to be different in as much as the hypes.json contains parameters not included in kittiBox.json and references python files not included in github, e.g., decoder/yolo_ish.py.

there seem to be 3 instances of each file type.  for example:

yolo_ish.py (referenced in hypes.json)
objective.py (in model_files directory)
decoder/fastBox.py  (in github)

what is the relationship between these?

thanks!

**Comment by MarvinTeichmann** [comment]
Hi,

during the initialize training folder phase, all files named in `hypes['modes']` are copied to `model_files` and given a standardized name. This allows to easily re-train, fine-tune and evaluate older versions of the model. So `objective.py` is the  "objective_file" of `Kittibox_pretrained` which is a copy of `yolo_ish.py` as referenced in `hypes.json`. 

`FastBox` is a refractured Version of `yolo_ish.py`. The file was restructured to make it much easier to understand. The code should be equivalent. The old run of KittiBox was included for documentation purpose. `Kittibox_pretrained` is part of the experiment published in our [paper](https://arxiv.org/abs/1612.07695).

**Comment by BenMacKenzie** [comment]
got it.  thanks.
