### ISSUE TITLE
About MultiNet

### ISSUE THREAD

**Issue by lbin** [MarvinTeichmann/KittiBox#8]
Hi Marvin

MultiNet is a very amazing job, will you have some plans to release the codes?
Or could I do some contribution based on your codes?

Looking forward to your replay!

**Comment by MarvinTeichmann** [comment]
Hi lbin,
I am glad that you like my project. I am on it ;). KittiSeg and KittiBox are submodules of MultiNet. Releasing those repositories over the last couple of weeks were first steps towards releasing MultiNet. Providing scripts and docu to make code easily useable takes some time unfurtionatly.

**Comment by lbin** [comment]
Thanks for your reply. Be willing to help anytime:)

**Comment by MarvinTeichmann** [comment]
@lbin, the multinet code is now public and can be found [here](https://github.com/MarvinTeichmann/MultiNet).

**Comment by lbin** [comment]
Thanks for reminding me, I will try it ASAP!
