### ISSUE TITLE
 Couldn't read: 007000.txt of ground truth.

### ISSUE THREAD

**Issue by YYZhangJason** [MarvinTeichmann/KittiBox#9]
When I am running train.py，I get some errors.
ERROR: Couldn't read: 007000.txt of ground truth. Please write me an email!
An error occured while processing your results.
Please make sure that the data in your zip archive has the right format!

Why?
Thanks!

**Comment by MarvinTeichmann** [comment]
This error message is printed by the [Kitti Evaluation code](https://github.com/MarvinTeichmann/KittiBox/blob/master/submodules/KittiObjective2/README.md). Most likely this means, that you did not download 
"data_object_label_2.zip". Did you run `download_data.py`?

**Comment by YYZhangJason** [comment]
I run download_date.py,errors:
2017-02-19 21:38:33,851 ERROR Wrong url.
2017-02-19 21:38:33,851 ERROR Please visit: http://www.cvlibs.net/download.php?file=data_road.zip
2017-02-19 21:38:33,851 ERROR and request Kitti Download link.
2017-02-19 21:38:33,851 ERROR Rerun scipt using'python download_data.py --kitti_url [url]'

sorry ,I am a novice,so I have many problems.Thanks

**Comment by YYZhangJason** [comment]
download from  this website:http://www.cvlibs.net/download.php?file=data_road.zip???

**Comment by MarvinTeichmann** [comment]
You need to do Step 4 of the readme. That is:
1. Follow this link: [http://www.cvlibs.net/download.php?file=data_object_image_2.zip](http://www.cvlibs.net/download.php?file=data_object_image_2.zip)
2. Enter your email address in the field. You will receive an email containing the actual download URL.
3. You will get an email with the actual download URL.
4. run `python download_data.py --kitti_url $URL_YOU_RETRIEVED`

where you replace $URL_YOU_RETRIEVED with the URL you got emailed.

**Comment by YYZhangJason** [comment]
Thanks
